INSERT INTO aseguradora(nombre) VALUES ('Quálitas');
INSERT INTO aseguradora(nombre) VALUES ('GNP');
INSERT INTO aseguradora(nombre) VALUES ('AXA');
INSERT INTO aseguradora(nombre) VALUES ('Seguros Banorte');
INSERT INTO aseguradora(nombre) VALUES ('HDI');
INSERT INTO aseguradora(nombre) VALUES ('Seguros Inbursa');
INSERT INTO aseguradora(nombre) VALUES ('Seguros El Águila');
INSERT INTO aseguradora(nombre) VALUES ('Migo');
INSERT INTO aseguradora(nombre) VALUES ('Mapfre');
INSERT INTO aseguradora(nombre) VALUES ('Aba Seguros');
INSERT INTO aseguradora(nombre) VALUES ('Seguros Atlas');
INSERT INTO aseguradora(nombre) VALUES ('Zurich');
INSERT INTO aseguradora(nombre) VALUES ('Afirme Seguros');
INSERT INTO aseguradora(nombre) VALUES ('AIG');
INSERT INTO aseguradora(nombre) VALUES ('ANA Seguros');
INSERT INTO aseguradora(nombre) VALUES ('La Latino Seguros');
INSERT INTO aseguradora(nombre) VALUES ('General de Seguros');
INSERT INTO aseguradora(nombre) VALUES ('Seguros El Potosí');
INSERT INTO aseguradora(nombre) VALUES ('Chubb');
INSERT INTO aseguradora(nombre) VALUES ('Ve Por Más');
INSERT INTO aseguradora(nombre) VALUES ('Allianz');
INSERT INTO aseguradora(nombre) VALUES ('RSA');
INSERT INTO aseguradora(nombre) VALUES ('ING');
INSERT INTO aseguradora(nombre) VALUES ('AVIVA');
INSERT INTO aseguradora(nombre) VALUES ('PlusUltra');
INSERT INTO aseguradora(nombre) VALUES ('USAA');
INSERT INTO aseguradora(nombre) VALUES ('Verti');
INSERT INTO aseguradora(nombre) VALUES ('Asefa Seguros');
INSERT INTO aseguradora(nombre) VALUES ('Multiva');
INSERT INTO aseguradora(nombre) VALUES ('Primero Seguros');
