INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('NSX','2002','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MR2','2000','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MKX','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('7 Series','2008','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Diamante','1996','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('H3','2010','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('IPL G','2012','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Optima','2011','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tacoma','2012','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Solstice','2007','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Firebird','1967','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Celica','2004','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Escort','1996','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Charger','2008','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Grand Am','1991','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Wrangler','2000','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('QX','2001','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('i-350','2006','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('F350','2009','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Villager','1994','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tacoma Xtra','2000','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Armada','2010','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Skyhawk','1989','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Legacy','2009','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Scoupe','1994','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Defender 110','1993','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MKS','2012','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Five Hundred','2006','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Esprit','2004','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Diablo','1991','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Daewoo Lacetti','2006','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Maxima','1999','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tribute','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Rondo','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('2500','1998','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('SVX','1994','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('I','1998','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('A6','2005','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram Van 1500','1999','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Freestar','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Daewoo Lacetti','2008','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Yukon','1998','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('F250','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Accord','1989','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('240SX','1997','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Samurai','1993','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('RX-7','1988','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('NSX','1998','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Trans Sport','1997','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Trans Sport','1993','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tacoma','2006','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('626','1992','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MDX','2001','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Probe','1991','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Altima','2000','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LS','2005','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('200','1991','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Brougham','1992','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tempo','1993','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Trooper','1998','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('TT','2012','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Discovery Series II','2001','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Protege','1992','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LS','1991','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Trooper','2000','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('X6 M','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Continental','1993','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Santa Fe','2004','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Montana','2002','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Challenger','2009','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Odyssey','2007','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S8','2009','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('SLK-Class','2011','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('H1','1997','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('DBS','2009','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tahoe','1996','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Mazda3','2010','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Express 2500','2003','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Integra','1999','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('9-3','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Swift','1994','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Escape','2007','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Bonneville','1985','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Impreza WRX','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Catera','1999','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Malibu','2013','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Range Rover Sport','2011','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('G-Series G20','1993','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Explorer','1993','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sunfire','2001','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Continental','2007','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('XF','2009','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram 3500 Club','1996','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MKS','2009','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GranTurismo','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('HHR','2008','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ion','2005','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Grand Caravan','2006','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Arnage','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('C-Class','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('C70','2003','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Aerostar','1993','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sonoma Club Coupe','1994','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Malibu','1999','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Town Car','2006','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MKX','2011','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Mustang','1970','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('M3','2012','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Allroad','2002','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Esprit','2002','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('2500 Club Coupe','1997','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Versa','2007','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('1 Series','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Grand Prix','1992','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Landaulet','2009','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Matrix','2009','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('CTS-V','2012','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Colorado','2010','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('G','1992','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Freelander','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('E150','2009','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('F-Series','1993','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('E150','2012','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Boxster','2002','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Type 2','1985','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MDX','2011','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tahoe','2010','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('6000','1984','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Passat','1991','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Esprit','1987','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Civic','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Insight','2012','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram 2500 Club','1997','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('A4','2003','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LHS','1996','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Crown Victoria','2005','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Skylark','1986','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GTO','1970','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('CTS','2006','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sienna','1999','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('C70','2002','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('RSX','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('280ZX','1979','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Accord','1990','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('5000S','1985','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LR4','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Swift','1991','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Firebird','1993','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Esprit','1992','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Liberty','2011','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Swift','1990','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('4Runner','2008','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Malibu','2011','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Q','1995','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Truck','1985','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Enclave','2012','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sonata','2009','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Range Rover Sport','2007','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('XL-7','2003','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('A6','1997','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('4Runner','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Prelude','1997','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Range Rover','1988','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('929','1994','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Tredia','1987','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Rapide','2010','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Supra','1993','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Cultus','1985','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Corvette','1993','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Allroad','2005','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('F-Series','2002','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('458 Italia','2010','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Neon','1999','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Contour','1997','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('G-Series G10','1992','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('E-Class','2005','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Grand Am','1999','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Park Avenue','1996','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Discovery','2008','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Charger','2010','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Pilot','2006','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Express 2500','1997','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('XC70','2006','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Town Car','1993','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('760','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LX','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('530','2003','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Reno','2007','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('SL-Class','2003','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S-Class','1987','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('I','2002','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Civic','2006','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Leone','1989','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram Van 2500','2002','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Highlander','2004','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Echo','2005','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('M-Class','1998','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Aveo','2010','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('100','1989','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('57','2008','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Quest','1994','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Corolla','2005','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('RX Hybrid','2012','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Continental GTC','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Suburban 2500','1996','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LeMans','1993','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S-Class','1998','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Explorer','2005','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Passat','2002','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Genesis','2011','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('RVR','1993','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Land Cruiser','2008','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Challenger','2008','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Firebird Formula','1992','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Dakota','1993','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('944','1985','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Vision','1994','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Aerio','2003','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram 1500 Club','1998','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Prelude','1994','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Suburban 1500','2006','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GS','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Parisienne','1985','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Santa Fe','2010','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Alcyone SVX','1992','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GTI','1991','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ram Van B250','1994','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Neon','1998','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GTO','1971','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Savana 1500','1999','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Avalanche 2500','2002','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Skylark','1987','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Avenger','1999','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Karif','1989','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Cobalt SS','2008','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Malibu','2002','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('2500 Club Coupe','1993','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('E-Series','2006','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Concorde','1993','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sable','1988','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S70','1998','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('GS','2002','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('5000S','1988','2',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Suburban 1500','2008','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Continental','1988','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Caprice','1994','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('B-Series Plus','2004','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sienna','1998','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Sierra 3500','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Corolla','2001','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MP4-12C','2012','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Villager','2001','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Rodeo','1992','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S-Class','2003','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Discovery','2004','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('3 Series','2007','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Silverado 1500','2005','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('C-Class','1996','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Roadmaster','1996','4',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Jimmy','1996','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('8 Series','1997','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Bronco','1986','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Forester','2003','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Galant','1990','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Explorer','2011','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Edge','2012','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('QX','2006','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S2000','2000','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Xterra','2004','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LX','2008','2',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('900','1999','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Seville','1995','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Xterra','2012','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('CTS','2010','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Riviera','1987','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Ranger','2000','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Montana SV6','2006','6',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Corrado','1990','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('4000CS Quattro','1987','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Silverado 1500','2007','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Impreza','1997','4',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('LeMans','1966','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Suburban 2500','2005','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Escalade ESV','2009','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('SL-Class','2011','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('riolet','1992','6',2);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Altima','2009','4',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('F150','2011','2',4);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Durango','2001','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('S-Class','2001','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Pacifica','2004','6',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Town Car','1991','2',8);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('740','1992','6',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('MDX','2012','4',6);
INSERT INTO capacidadCoche(modelo,anio,puertas,pasajeros) VALUES ('Golf','1988','4',8);
