INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tlapanalá','Consejo Agrarista Mexicano I','La Venta',2630,34035);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Nicolás Romero','El Retoño','Verín',5445,44541);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Zapotlanejo','Demet (U Hab)','Sandía',4356,33043);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Españita','Arboledas Del Sur','Otomíes',8287,96881);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Tuzantán','Altillo (Cond Altillo Universidad)','De La Salud',3539,46872);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Atotonilco de Tula','Concordia Zaragoza (U Hab)','Laura',2004,46846);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Baja California','Mexicali','Calzada Jalalpa','Aarón Proal',6560,45882);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Bartolomé Quialana','El Pocito','Verde',5151,28956);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Jiménez','Acacias','Acoxpa',8246,49131);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tabasco','Jalpa de Méndez','El Ermitaño','Valle Nogal',7230,79478);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Campeche','Calakmul','Bosques De Tarango','Circuito Interior',2168,80913);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Oaxaca de Juárez','Batan Viejo (El Maestro)','Eren Jaeger',3095,37718);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Atzitzintla','Ctm Viii Culhuacan (U Hab)','Panticosa',9876,85326);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Coyuca de Catalán','Centro Vii','La Divina Comedia',5973,91968);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Chiconquiaco','Centro Ii','Águila Triana',8065,12579);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Sacramento','Allepetlali (U Hab)','De La Alborada',592,47540);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xochiltepec','America','Ámsterdam',2037,41270);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Domingo Arenas','El Zacaton','Villa Alberdi',8210,21141);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Aguascalientes','Cosío','El Pirul','Verbena',2716,47072);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tepehuacán de Guerrero','Albert','Daniel Valgañón',4790,61172);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San José Estancia Grande','El Santuario (Ampl)','Victoria',2318,85426);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Catarina Loxicha','Acueducto','Adolfo López Mateos',6834,64343);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Jerez','El Capulin (Ampl)','Valenzuela',6565,77961);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Nanchital de Lázaro Cárdenas del Río','El Prado','Vereda 75',2037,43677);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Mazamitla','Bosque Residencial Del Sur (Fracc)','Calzada de los Misterios',7105,33784);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tianguismanalco','Adolfo Ruiz Cortines Ii','Artes',6334,94002);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Bacanora','El Triunfo','Viella',5897,76877);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Acateno','El Molinito','Vélez',4392,80054);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Zontecomatlán de López y Fuentes','El Arenal Pto Aereo (Fracc)','Unión De Colonos',8444,59299);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Joquicingo','Anahuac I','Miguel de Cervantes Saavedra',3270,36565);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Texcatepec','Centro Urbano Presidente Aleman (U Hab)','Laboristas',6886,81397);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Evangelista Analco','Chinampas De Santa Ma Tomatlan','La Planta',2125,66638);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Dzilam de Bravo','Buenavista Ii','Eje 10 Sur',3552,39985);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Huejuquilla el Alto','Cañada Del Olivar (U Hab)','Abraham González',1817,50506);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tepanco de López','El Arbolillo','Santa Cruz',9083,30007);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Magdalena Apasco','Allepetlali (U Hab)','De La Alborada',3532,11197);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Cuautla','Centro I','Águila Blanquinegra',624,52737);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Mazatlán Villa de Flores','Ctm Ixa Culhuacan (U Hab)','Paloma',7451,91370);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Amecameca','Boscoso (U Hab)','Calzada de Guadalupe',6453,53566);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Bartolo Soyaltepec','Campestre Potrero','Abertal',8869,61527);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Teopoxco','Desarrollo Urbano Quetzalcoatl Ii','San Felipe De Jesús',7911,80968);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Cristóbal Amatlán','El Rosario','Vicente D. Lugo',2231,42188);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','General Heliodoro Castillo','Del Mar Norte','Salvador Guzmán',5986,20746);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Bacanora','Casas Aleman (Ampl) Ii','A. Gómez',280,93130);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Tonila','Degollado','Sagú',8204,76599);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Monterrey','Benito Juarez','Avenida Revolución (Ciudad de México)',3728,55988);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','Amatlán de Cañas','Chalma De Guadalupe Ii','La Joya',7850,72559);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Monterrey','Cacalote','Río de la Piedad',7588,11786);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Pilcaya','Allepetlali (U Hab)','De La Alborada',2590,92004);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','General Enrique Estrada','Chinampac De Juarez Iii','La Peña',7697,83654);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Huichapan','Cazulco (Barr)','Agrónomos',6754,24852);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Ana del Valle','Consejo Agrarista Mexicano I','La Venta',3114,33499);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Quintana Roo','Solidaridad','Cristo Rey','Palmarola',8385,69653);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Miguel del Puerto','Ctm Ixa Culhuacan (U Hab)','Paloma',5963,97377);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Temaxcaltepec','Art 4to Constitucional (U Hab)','París',1798,44519);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Naucalpan de Juárez','Ejto Constitucionalista','Santa Bárbara',9688,28064);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Ocampo','Desarrollo Urbano Quetzalcoatl Iii','San Francisco',9110,52175);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Cuernavaca','Atlamaxac','Primera EJido',7374,75892);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','General Zaragoza','2a Ampliacion Santiago Acahualtepec I','Simón Bolivar',8526,58165);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Ahuatlán','Agua Bendita','Aztecas',8268,94063);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Santiago','El Rosal','Vicente Dávila',4654,36697);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','San Carlos','El Arbolillo 1 (U Hab)','Santa Cruz Meyehualco',6499,79942);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Pánuco','Cafetales I (Rdcial)','Viaducto Miguel Alemán',276,43670);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Acatlán','Belem (Barr)','Segunda Cerrada',3242,93592);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Marcial Ozolotepec','Adolfo Lopez Mateos','Alberto Zamora',8443,38353);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Peto','Damian Carmona','Pastor Rouaix',6105,15594);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Villaldama','Emiliano Zapata','Villa Alcolea',1374,70816);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xayacatlán de Bravo','Anahuac Dos Lagos','Campos Elíseos',4135,30799);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Xico','Condominio Del Bosque (Fracc)-Bosque De Tlalpan','Laurel',7732,93231);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Uayma','Campo De Tiro Los Gamitos','Abetos (Pacanas)',3756,90560);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Quiriego','El Divisadero','Valle Fresno',1539,58672);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Bacerac','Agricola Oriental V','Avenida Miguel Hidalgo',6024,42138);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','La Yesca','El Capulin','Valentín Gómez Farías',7566,72649);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Simón Zahuatlán','Cuatro Arboles','Paradero',2334,38210);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Ayapango','Centro I','Águila Blanquinegra',6577,22051);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Felipe','Damian Carmona','Pastor Rouaix',8266,24276);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','San Salvador','Coyuya (Fracc)','Palafox',8587,96779);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Pisaflores','Cuchilla De Padierna','Parque',3247,44731);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Ixhuatán','Bahia (U Hab)','Laguna de Términos',3498,57670);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Jerónimo Silacayoapilla','El Batan','Vainilla',7352,27340);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Matachí','Anahuac Lago Norte','Ejército Nacional',3499,68127);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Matías Tlalancaleca','Atacaxco','Pedro Arvizu',3925,84698);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Ciudad Valles','Cuchilla Del Tesoro','Parral',4701,78278);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','La Huacana','Bosque Residencial Del Sur (Fracc)','Calzada de los Misterios',3477,24853);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Las Rosas','Demet (U Hab)','Sandía',3305,69608);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Quintana Roo','Arboledas Del Sur','Otomíes',1134,34387);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Zacazonapan','Cooperativa Cehuayo','Pablo Galeana',7523,31660);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Zinacantán','Cove','Palacios',5383,17693);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Ixhuatlán del Café','Aragon La Villa (Aragon)','Omega',2102,77814);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tlaola','El Rosario','Vicente D. Lugo',5005,74215);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Degollado','El Vergel Triangulo De Las Agujas I (U Hab)','Villa',3491,85960);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Cuyoaco','Aztlan (U Hab)','Laguna de Tamiahua',845,33010);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Chihuahua','Concordia Zaragoza (U Hab)','Laura',7718,60632);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Vicente Guerrero','Ejidos San Juan De Aragon 1a Seccion (U Hab)','San Rafael Atlixco Eje 4 Sur',6827,68962);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Catarina Quiané','Ejto Constitucionalista Ii (U Hab)','Santa Catalina De Sena',6065,17669);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Unión Hidalgo','Altos Tepetlica','De Las Arboledas',4809,53631);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Teotihuacán','Agricola Oriental V','Avenida Miguel Hidalgo',2646,79996);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Ahuacatlán','El Carmen','Valle De Guadalupe',3011,57567);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Yaá','Ampliacion San Francisco Culhuacan (Ej)','Masaryk',7783,94591);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Mecayapan','Agricola Oriental Ii','Avenida del Panteón',3290,85371);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Chihuahua','Barranca Seca','San Álvaro',4297,20059);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','El Espinal','Dm Nacional','San Ignacio (Guadalupe Borja)',4344,93767);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tlanchinol','Adolfo Ruiz Cortines I','Arquitectura',8935,20408);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Chikindzonot','Ajusco Huayamilpas','Bugambilia',1386,32275);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Juan Atenco','2a Ampliacion Santiago Acahualtepec Ii','Isabela Católica',2841,63784);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Chiconquiaco','Citlalli','Larga Distancia',6283,60991);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Magdalena Tlacotepec','Ctm V Culhuacan (U Hab)','Panchicalco',7885,10644);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Jalpa','Citlalli','Larga Distancia',8364,79906);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Colima','Comala','Consejo Agrarista Mexicano Ii','Lazarillo De Tormes',458,32355);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Colima','Comala','Alamos Ii','Dalias',4884,89265);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tlanalapa','Casas Aleman (Ampl) I','Agave',1142,54930);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Colima','Cuauhtémoc','Cuautepec El Alto (Pblo)','Parota',7827,44256);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Antonio Cañada','Claveria','Las Américas',9325,60520);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Comaltepec','Ejto Constitucionalista,Supermanzana I (U Hab)','Sansores Pérez',6578,32324);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Tidaá','Centro Iv','Agujas',1047,18761);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Durango','Nombre de Dios','Altillo (Cond Altillo Acasulco)','Del Arco',3645,73021);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Durango','Cuencamé','Barros Sierra','Santa Rosa',2501,32263);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Luis Amatlán','El Vergel','Viesca (Cuarta De Ortega)',5991,99090);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Huejuquilla el Alto','Ejto Constitucionalista,Supermanzana I (U Hab)','Sansores Pérez',9053,58946);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Jocotepec','Claveria','Las Américas',6562,19683);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Amatenango del Valle','Colinas Del Bosque-Las Tortolas','Las Rosas',4387,60716);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Jonacatepec','Buenavista I','Eje 3 Norte',5952,39626);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Abalá','El Arbolillo 2 (U Hab)','Santa Elena',2009,97260);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Cohetzala','24 De abril','Cuamiagua',4665,24852);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Chumayel','Carmen Serdan','Afrodita',4274,96928);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','San Joaquín','Cuatro Arboles','Paradero',757,14855);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Arteaga','Centro Urbano Tlalpan (U Hab)','La Central',2581,81482);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Chilón','Cedro Chico','Agua Prieta',645,52932);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Puente Nacional','Ctm Viii Culhuacan (U Hab)','Panticosa',5905,42123);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Atitalaquia','Atlampa','Rafael Oliva',3047,20589);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Apan','Alianza Popular Revolucionaria Norte (U Hab)','Décimo Séptimo',7916,83263);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tabasco','Centla','Copilco Universidad','Pablo Picasso',389,24688);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Santa Isabel Xiloxoxtla','El Eden','Valle Nacional',2303,96449);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Catarina Cuixtla','Doctores V','San Juan',1222,24584);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','San Lucas','Ejto De Ote Ii (U Hab)','Santa Cecilia',6248,64696);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Uriangato','Centro De Azcapotzalco','Aguascalientes',3484,21205);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Xaltocan','Daniel Garza','Patatlán',7967,73383);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Comaltepec','El Arbolillo','Santa Cruz',6857,29599);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Ayala','Candelaria De Los Patos (U Hab)','Acambay',5000,39859);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','Tecuala','El Parque De Coyoacan (Fracc)','Veracruz',3993,25012);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Ecatepec','2a Ampliacion Santiago Acahualtepec Ii','Isabela Católica',5174,68882);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Mazatán','Barrio Norte','San Francisco',8719,24377);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Chontla','Cafetales Ii (Rdcial)','Avenida Plan de Ayala',4983,60428);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','Pinal de Amoles','El Zacaton','Villa Alberdi',3242,77994);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Ocotlán','Cerro De La Estrella Ii','La Gloria',2376,77149);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Puente de Ixtla','Atotolco','Rancho Escondido',750,93081);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Acatlán de Juárez','Cañada Del Olivar (U Hab)','Abraham González',58,52923);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','San Ciro de Acosta','Dm Nacional','San Ignacio (Guadalupe Borja)',1048,32507);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Quiatoni','Cuitláhuac 1 Y 2 (U Hab)','Pasillo 5',4186,81728);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Nazareno Etla','El Gavillero','Vaquero',2031,15685);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Cruz Amilpas','Emiliano Zapata','Villa Alcolea',5845,17609);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Atlixco','24 De abril','Cuamiagua',3687,27482);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Chicontepec','Ecologica Novedades Impacto (U Hab)','San Marcos',7305,73769);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Yosondúa','Copilco El Alto','Pablo L. Rivas Martínez',4299,90249);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Tarimoro','El Divisadero','Valle Fresno',7875,14106);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Cortazar','Del Obrero','Samuel Crompton',2131,47650);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Huiloapan de Cuauhtémoc','Ahuatenco','Berlín',9910,94583);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Catarina Lachatao','Del Bosque','Salsifí',207,38612);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tuxpan','Agricultura','Azaleas',3783,22150);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Calcahualco','Del Carmen','Salvador Allende',3752,71916);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Bachíniva','Carlos Pacheco (U Hab)','Aeronautas',1794,81238);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Reyes Etla','El Triangulo','Viela',5595,61565);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Queréndaro','El Carmen','Valle De Guadalupe',4906,95570);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Quiegolani','Dos Rios','San Juanico',1600,50137);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pablo Yaganiza','Canal Once (U Hab)','Acahuatl',7031,93202);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Ciudad Ixtepec','Campestre Coyoacan (Fracc)','Abelardo L. Rodríguez',5512,31897);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Ocozocoautla de Espinosa','Campestre Coyoacan (Fracc)','Abelardo L. Rodríguez',6852,14627);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Quimixtlán','Del Gas (Ampl)','Salvador Escalante',3620,69759);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Santa Apolonia Teacalco','Arcos De Centenario','Pablo de la Llave',4952,84161);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Filomeno Mata','Chapultepec Morales (Polanco)','La Loma',1950,39846);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Chicomuselo','El Yaqui','Villa Alazán',9820,20472);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Candelaria Loxicha','Cruz Roja Tepantongo (U Hab)','Palmillas',1568,23883);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Atzalan','Citlalli','Larga Distancia',7392,46096);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Miguel de Allende','Altillo (Cond Altillo Acasulco)','Del Arco',348,75055);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Ozumba','Chinampac De Juarez Iii','La Peña',9265,64470);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tancítaro','Ampliacion Miguel Hidalgo 2a Secc','Alfonso Reyes',1893,80534);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Mazatán','Agricola Metropolitana','Atenas 1906',7216,60195);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','José Sixto Verduzco','7 De Julio (Ampl)','República de Bolivia',2504,43853);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Ixtapan de la Sal','Altos Tepetlica','De Las Arboledas',78,24984);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Jiquipilco','Atocpa Sur','Rancho del Sol',5549,71044);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Baltazar Chichicápam','El Contadero','Valle De México',6370,76503);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Santa Catarina','El Rosario','Vicente D. Lugo',9457,33135);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Sochiápam','Centro I','Águila Penachuda',3303,93311);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Ánimas Trujano','Canutillo Predio La Presa','Acíbar',3021,96605);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Teotongo','Coltongo','La Troje',8114,37740);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Ildefonso Villa Alta','Cruz Blanca','Palmeras',5949,71894);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Emiliano Zapata','El Pirul','Verbena',3037,92604);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tlacuilotepec','Alfonso Xiii','Décimo Octavo',6630,55387);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Palmillas','Aguilas Pilares','Beisbol',4862,70802);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Tepetongo','Ejercito De Agua Prieta','San Nicolás',1197,66929);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Senguio','Amsa','Emilio Castelar',3470,68874);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Juárez','Acuilotla','Agave',5496,24329);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Ixcuintepec','El Arbol','Santa Coleta',7841,10894);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Quitupan','El Prado','Vereda 75',2824,26003);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Yaveo','Canutillo 3ra Seccion','Aciano',9881,22781);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','San Gabriel','Cuitlahuac','Paseo Galias',7809,84808);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Sebastián Coatlán','El Arenal 4a Seccion','Unión',8311,82206);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Coyotepec','Cruz Blanca','Palmeras',5376,50708);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','Rosamorada','Desarrollo Urbano','San Esteban',1018,51177);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Bautista Valle Nacional','Colinas Del Sur','Las Torres',2001,21642);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tecamachalco','Degollado Chico','Salitrillo',112,49625);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Etchojoa','Chinampac De Juarez I','La Palma',7075,42106);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Sain Alto','El Arenal 2a Seccion','Unidad Modelo',9410,39161);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','José Joaquín de Herrera','El Rodeo','Veterinarios',8865,69996);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Xochihuehuetlán','Eduardo Molina Ii (U Hab)','San Mateo',2429,69370);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Jerónimo Tlacochahuaya','Cosmopolita','Paisajistas',921,74343);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Huautla','El Sifon','Victoriano Cepeda',3700,53734);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Santa María del Río','Campestre Coyoacan (Fracc)','Abelardo L. Rodríguez',7694,92649);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Pochutla','Cuautepec De Madero','Paricutín',9515,31305);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Ajalpan','El Retoño','Verín',8235,33173);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Mochitlán','Ejidos De San Pedro Martir Ii (Sur)','San Rafael Atlixco',6112,80224);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tlanchinol','El Mirador - Santa Catarina','Vejarano',2434,79912);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Zamora','2a Ampliacion Santiago Acahualtepec I','Simón Bolivar',4729,54515);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Distrito Federal','Iztacalco','Ctm Viia Culhuacan (U Hab)','Pantaleón García',5220,45351);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Lachixío','Bondojito','Callejón de Manzanares',4626,10787);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Técpan de Galeana','Atenor Salas','Pedro Díaz',9038,68547);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Tancoco','Ajusco Huayamilpas','Bugambilia',6173,62267);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Jacala de Ledezma','Bosques De Las Lomas','Calzada Ignacio Zaragoza',7998,85747);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Tumbalá','Arboledas De Cuautepec (Ampl)','Osa Menor',3087,93708);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Ayutla de los Libres','Diamante','San Ignacio',2949,23128);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tetepango','Belisario Dominguez','Avenida Chapultepec',2289,92441);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','León','Aidee Solís Cárdenas-Matías Romero (U Hab)','Buenavista',9789,74637);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Quimixtlán','Ejidos De San Pedro Martir Ii (Sur)','San Rafael Atlixco',2673,29312);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Tanlajás','Bosques De Las Lomas','Calzada Ignacio Zaragoza',4905,50042);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Jerónimo Taviche','Adolfo Lopez Mateos','Alba',5914,72294);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Dinicuiti','Centro Iii','Aguirre B.',2082,47614);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','La Huerta','Alianza Popular Revolucionaria Poniente (U Hab)','Décimo Tercero',5814,56573);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Acuña','Cuauhtemoc Pensil','Paraje Meyehualco',3730,72660);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','San Lucas Tecopilco','Centro Iv','Agujas',8381,11622);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Juan Aldama','Antorcha Popular I (U Hab)','Francisco Sosa',7828,62449);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Campeche','Palizada','Desarrollo Urbano Quetzalcoatl Iii','San Francisco',4247,31294);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Jojutla','Casa Blanca','Agárico',8138,30788);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Evangelista Analco','Chichicaspatl','La Manzana',6905,84349);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Mateo Peñasco','El Caracol','Valle De Bravo',3979,83142);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Mártir Quiechapa','Del Valle Iv','San Ángel',7671,76730);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Chiconcuautla','Ctm Ixa Culhuacan (U Hab)','Paloma',1129,31089);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Nicolás Bravo','Caltongo (Barr)','Morelos Sur',4472,99644);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Bartolomé Yucuañe','Colinas De Tarango','Las Peñas',6511,95426);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Xaloztoc','Asturias (Ampl)','Pedregal',5577,90351);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tenango de Doria','El Zacaton','Villa Alberdi',9900,45956);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Las Minas','Ampliacion Lomas De Padierna','Parque España',7327,74538);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Santa Isabel','25 De julio','Delta',2416,79631);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','El Marqués','Carlos Hank Gonzalez','A. De Córdoba',739,77448);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','San Martín Chalchicuautla','El Paraiso','Venus 2',672,62755);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Mazapil','Degollado','Sagú',9716,17969);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Momax','Cuauhtemoc Pensil','Paraje Meyehualco',3733,96514);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Doctor Arroyo','Acueducto De Guadalupe (Rdcial)','Adolfo Ruiz Cortines',7540,41794);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Aldama','Del Valle V','San Antonio',3064,14876);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Cieneguilla','Cuadrante De San Francisco','Papaya',4259,95592);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Kanasín','Alfonso Xiii','Décimo Octavo',5238,18272);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María la Asunción','Cantera Puente De Piedra','A. Castro',9497,99945);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Temamatla','Chinampac De Juarez I','La Palma',8434,83479);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Quintana Roo','Othón P. Blanco','Ejidos De San Pedro Martir Ii (Sur)','San Rafael Atlixco',3281,27075);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Yahualica','Del Niño Jesus (Barr)','Salvador V.',282,80259);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tepetitlán','Batallon De San Patricio (U Hab)','Santa Úrsula',3524,94577);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Otatitlán','El Rosario B (U Hab)','Vicente Guerrero',6192,64953);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Buenavista de Cuéllar','El Tanque','Víctor Iturbe',2410,74813);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','General Canuto A. Neri','Caracol','Actopan',4046,27096);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Ciudad Madero','Doctores I','San Isidro',5628,76689);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Tepetlapa','Aguilera','Benito Juárez',6825,21921);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Nicolás de los Ranchos','Coltongo','La Troje',9579,22218);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Gómez Farías','El Manto-Plan De Iguala','Vázquez',3840,38300);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Torreón','Colonial Iztapalapa (Fracc)','Las Tres Cruces',6219,62918);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xayacatlán de Bravo','Arboledas Politoco','Ozolotepec',2317,58186);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Axochiapan','Cuauhtemoc Pensil','Paraje Meyehualco',7472,59600);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Cumpas','Belisario Dominguez','Avenida Chapultepec',1353,15046);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Sinaxtla','12 De diciembre','Correo Mayor',5572,51341);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Ecatepec','El Rodeo','Veterinarios',798,77078);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Blas Atempa','Bosque De Tepeximilpa','Calzada de la Viga',5069,84156);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Durango','San Juan del Río','Agricola Oriental Ii','Avenida del Panteón',3054,98080);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sinaloa','Mocorito','El Pirul','Verbena',7293,70589);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Cosoltepec','Cuchilla Pantitlan','Pascual Ortiz Rubio',1700,18952);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Villa Díaz Ordaz','Coapa 2a Seccion-Ramos Millan','Las Flores',5963,29282);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Camotlán','Barranca Seca','San Álvaro',8139,71071);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Tomatlán','El Molino_','Venecia',4170,79011);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Tierra Blanca','Aztlan (U Hab)','Laguna de Tamiahua',5091,86269);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Huautla de Jiménez','El Mirador','V. Bravo',2090,79511);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xochiltepec','Del Mar Norte','Salvador Guzmán',9278,49917);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Celaya','Centro Viii','La Era',123,66343);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Cotija','Anahuac Peralitos','Goma',5629,62011);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Jiménez','Constitucion De La Republica','Pabellón',5595,98909);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tula de Allende','Agricola Metropolitana','Atenas 1906',308,79597);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Nicolás','Del Bosque','Salsifí',8345,83438);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','El Salto','El Bosque Seccion Torres','Valentín Campa',1429,56741);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sinaloa','Navolato','Cananea (U Hab)','Acamapichtli',9841,78024);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Progreso de Obregón','7 De julio','República de Brasil',7468,46973);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','La Reforma','Atotolco','Rancho Escondido',604,25644);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Distrito Federal','Tlalpan','Demet (U Hab)','Sandía',9834,44213);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Celestún','Bondojito','Callejón de Manzanares',1470,14480);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Soledad Atzompa','El Caracol','Valle De Bravo',4628,65239);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Yatzona','Del Mar Norte','Salvador Guzmán',6697,11864);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Apazapan','Ampliacion Miguel Hidalgo 3a Secc','Tamaulipas',7832,82912);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Piedras Negras','Ahuehuetes Anahuac','Bruselas',4710,64956);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Colima','Villa de Álvarez','Eduardo Molina I (U Hab)','San Martín',2942,60911);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Cristóbal Amatlán','Aragon Inguaran','Olmeca',8862,79018);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Ana Tlapacoyan','51 Legislatura','Alfa',9363,25169);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Sinaloa','Badiraguato','Coltongo','La Troje',4380,46142);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santo Domingo Yanhuitlán','Acacias','Acoxpa',4635,68947);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Alpatláhuac','Belen De Las Flores Seccion Relleno','Avenida Álvaro Obregón',670,74427);
INSERT INTO dirCliente(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Temixco','Del Valle Iv','San Ángel',8044,52298);
