INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Hueytlalpan','Cabeza De Juarez I (U Hab)','Platino',3725,75228);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Coyotepec','Aviacion Civil (Ampl)','Ernesto Che Guevara',2292,60990);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pablo Villa de Mitla','Arturo Gamiz','Cerrada 28',8285,42749);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Villagrán','Condesa','Hda. De Corralejo',8527,68239);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','San Gabriel','1a Ampliacion Santiago Acahualtepec','Patzcuaro',3913,81092);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tianguismanalco','Asturias (Ampl)','San Lorenzo',7403,90397);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Florencio Villarreal','Capultitlan','Higinio Guerra',9971,22547);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Contla de Juan Cuamatzi','Del Mar Sur','Av. Central',9624,87897);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Magdalena Jicotlán','El Vergel Triangulo De Las Agujas Ii (U Hab)','Tuxtla Gutierrez',9991,82982);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Soledad Atzompa','Del Gas (Ampl)','Centeno',8746,18204);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Kopomá','Anahuac Ii','Coyotl',7872,95592);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Huaxpaltepec','12 De diciembre','Valle De Labores',5777,66708);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Santa Catarina','El Triunfo (Ampl)','Guadalupe Victoria',48,90667);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Teabo','El Yaqui','De Amaquixtle',5036,35961);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Chicomuselo','Carlos Pacheco (U Hab)','Las Coronelas',777,61482);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Empalme','Chalma De Guadalupe I','Agustín Melgar',2709,29887);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Diego de la Unión','Cristo Rey','Gral. Valentin Canalizo',2112,65859);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Campeche','Calkiní','Arroyo Guadalupe (U Hab)','Lago Atitlan',1441,29455);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Nahuatzen','Centro Viii','Potrerillos',3840,55412);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Chacsinkín','Acueducto De Guadalupe (U Hab)','Conahuatl',2670,33645);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Valle de Guadalupe','Club De Golf Mexico-San Buenaventura','Pataguas',2118,92809);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Apaxtla','El Vergel Triangulo De Las Agujas Ii (U Hab)','Hda. De Nopala',8879,22830);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Cañada Morelos','Año De Juarez','Primera Libertad',3305,39538);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Tonila','1ra Victoria Seccion Bosques','Palacio Nacional',7443,43132);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Guadalupe Victoria','Ave Real (Ampl)','Pino Suárez',9213,41667);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Coahuitlán','Aldana','Callejón Crucifixión',2993,45593);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Baca','Anahuac Lago Sur','Cocuatla',3725,92967);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','El Arenal','Ctm Viia Culhuacan (U Hab)','L. Melgarejo',6711,88231);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Lorenzo Victoria','24 De abril','A. Díaz Covarrubias',7538,73990);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Nácori Chico','Bosque De Tepeximilpa','Alcatras',8284,29624);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Cananea','Acacias','Agua Salada',4660,58457);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tlanalapa','Alvaro Obregon','Matlalzihuatzin',491,69497);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Lucas Camotlán','6 De junio','Adolfo López Mateos',9335,43510);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Piaxtla','Centro Ii','Privada 6-A',2701,51110);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Durango','Mapimí','Defensores De La Republica','Encinos',1230,64180);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Nicolás Romero','10 De mayo','Plazuela 16 De Av. De Las 3 Culturas',1658,66273);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Soledad Atzompa','Cerro Grande','Centeno',2791,91084);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Miguel Amatlán','Angel Zimbron','C',4796,37829);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tancítaro','Aculco (Pblo)','Pte. 13',2703,69888);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Huejuquilla el Alto','El Rodeo','Nte. 1',7469,83910);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Uriangato','El Rosedal I','Hda. Animas',1692,35664);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Matías Tlalancaleca','Batallon De San Patricio (U Hab)','República De Cuba',4099,86157);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Atempan','Centro Vii','Oriente 32',8562,13867);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xochiltepec','Barrancas De Guadalupe','Segunda',7509,33372);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Chicontepec','Aldana','Camino Arca De Noé',9751,43145);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Quechultenango','Diamante','Industrial',2910,67144);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Jojutla','Cooperativa Luis Enrique Rodríguez Orozco (U Hab)','Ret. B. Berlin',4515,21677);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','La Yesca','Cuchilla Pantitlan','Rosario',5502,76635);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Felipe Jalapa de Díaz','Barrio 18','Valle De Mackenzie',2213,34377);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tehuacán','El Reloj','San Ángel',7479,15532);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Magdalena','Adolfo Lopez Mateos','Ote. 10',3705,10287);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','General Zuazua','Cosmopolita (Ampl)','S. Esteban',4707,43977);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Sain Alto','El Rodeo','De San José',3173,66264);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Tenancingo','Alvaro Obregon_ (Fracc)','Plazuela 2 De Av. Plaza De La Constitución',1171,55428);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Malinalco','Aragon Inguaran','Plazuela 12 De Av. Plaza De Aragón',1483,47820);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Atitlán','Barrio La Lonja','Jazmín',6892,23729);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Miguel Ahuehuetitlán','Doctores V','Azalea',5975,84569);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Mérida','Ampliacion Miguel Hidalgo 4a Secc','Cristo',9473,97126);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Guadalupe','Centro Vii','Sicomoros',3045,99158);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Santo Domingo','Alpes (Ampl)','Voltaire',6516,56656);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','San Rafael','Desarrollo Urbano Quetzalcoatl I','Coa',5562,18815);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Villa González Ortega','Bahia (U Hab)','Dolores Hidalgo',4600,67702);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tuxpan','Del Niño Jesus (Barr)','Pte. 26',8373,53259);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Contepec','Del Valle Iv','Plazuela 5 De Av. Plaza De Aragón',7356,27721);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','Corregidora','Corpus Curisty Ampl Xocomecatla','Solidaridad Tejones',8884,61033);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Yecuatla','El Arenal 2a Seccion','Circuito Dos',7116,84640);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Hueytamalco','Doctores V','Plata',3857,45169);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Carichí','Agricola Oriental Vi','Cipreses',9771,76004);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','La Perla','Club De Golf Mexico-San Buenaventura','Cda. Rubí',4485,98429);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Benito Juárez','Aldana','Amapolas',1250,58414);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Teotilálpam','Doctores V','Valle Del Balsas',8685,58659);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Sabinas Hidalgo','Del Niño Jesus (Barr)','S. Pablo',6909,61132);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','General Bravo','El Arbolillo','Sauce',6637,36457);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santo Domingo Yanhuitlán','Conjunto Urbano Cuemanco (U Hab)','Mazahuas',1128,98672);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Ixhuatlancillo','Apatlaco','Caracol',5644,28571);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nayarit','Tecuala','Del Niño Jesus (Barr)','Romero Rubio',3485,71848);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Ameca','Ctm X Culhuacan (U Hab)','Moctezuma',5709,61722);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tabasco','Emiliano Zapata','Barrio Norte','Aminama',9107,16168);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tanhuato','Del Valle Iii','Pte. 15',8303,58986);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Guadalupe Victoria','Cerro Grande','Pino Suárez',6034,26027);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Pablo Anicano','Cabeza De Juarez Ii (U Hab)','Retama',2575,46585);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tula de Allende','Atlantida','Merida',1872,93312);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Las Choapas','Casa Blanca','Camino La Mina',5160,32521);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Ixtacuixtla de Mariano Matamoros','Chinampac De Juarez I','Atlixco',1948,56527);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Temoaya','Arboledas Politoco','Plazuela 2 De Av. Plaza De Aragón',1778,30839);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Otzolotepec','Cabeza De Juarez Iii (U Hab)','Plazuela 1 De Av. Plaza De La Constitución',444,79835);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Larráinzar','Adolfo Ruiz Cortines I','Acambay',7820,45037);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Texcalyacac','Carmen Serdan (U Hab)','Plazuela 2 De Plaza De San Jacinto',6944,70779);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Victoria','1ra Victoria Seccion Bosques','Hda. De Atenco',2611,42623);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Burgos','Dos Rios','Anenecuilco',9729,40750);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Trinidad García de la Cadena','America','Del Oro',5510,73017);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Matachí','51 Legislatura','Cond 19',6668,51989);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Jilotlán de los Dolores','Campestre Coyoacan (Fracc)','Ombules',8262,80471);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Atlautla','51 Legislatura','Periférico-Calle 7',9528,10774);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','El Mante','El Mirador - Santa Catarina','Arboleda',6726,88297);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Cruz Zenzontepec','De Tarango (Rncda)','Ejido De San Francisco',4836,34516);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Miguel Ejutla','Carola (U Hab)','Campesinos',1705,41745);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Nundiche','Ayocatitla,Asunción','Lázaro Cárdenas',5015,93899);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Tuxpan','Copilco El Bajo','Parotas',585,47024);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Ixtapangajoya','Chapultepec Morales (Polanco)','Abelardo L. Rodriguez',8982,27349);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Coahuila de Zaragoza','Torreón','Asturias (Ampl)','Lago Peipus',1301,63298);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Temascaltepec','Centro Urbano Tlalpan (U Hab)','Plazuela 2 De Av. De Las 3 Culturas',2246,66265);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Benito Juárez','5 De mayo','Amapolas',5647,11449);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','San Fernando','Chalma De Guadalupe I','Almoloya',3041,78155);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Acuamanala de Miguel Hidalgo','Castillo Grande (Ampl)','Av. División Del Nte.',6511,35919);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sinaloa','Escuinapa','Altillo (Cond Altillo Universidad)','Acoxpan',7497,68486);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Pihuamo','Atlantida','Ote. 2',5698,91226);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santo Domingo Xagacía','Ejidos San Juan De Aragon 2a Seccion (U Hab)','Mayos',9145,75447);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','Pedro Escobedo','1ra Victoria Seccion Bosques','Tarahumaras',8946,37433);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Mexicaltzingo','Coyuya (Fracc)','Plazuela 13 De Av. Plaza De Aragón',4490,72275);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Tonayán','Anahuac Mariano Escobedo','Chuanacatl',3910,99178);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Chihuahua','Ctm Vi Culhuacan (U Hab)','Cjon. De Veracruz',3103,24275);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Tamalín','Argentina Antigua','Central 29',5263,72320);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','La Grandeza','10 De abril','Las Palmas',7856,61858);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Sayula','Cedro Chico','Ote. 35',4705,38561);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Ixcatlán','Doctores Ii','Ferrocarriles',6617,60997);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','El Arenal','Ctm Vi Culhuacan (U Hab)','L. Melgarejo',5089,19100);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Chietla','Canutillo(Aguascalientes)','Orquídea',5780,98632);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Mazatlán','Condominio Del Bosque (Fracc)-Bosque De Tlalpan','Violeta',666,31688);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Otzoloapan','Chichicaspatl','Plazuela 1 De Av. Plaza De Aragón',2050,21192);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Taviche','Benito Juarez (Ampl)','Cobre',846,20583);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Francisco del Mar','Corredor Santa Fe','Valle De Mekong',7663,49788);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Chimalapa','Dm Nacional','Esperanza Sur',6769,30724);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Ana Cuauhtémoc','Cristo Rey','De Las Torres',9193,69400);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Petatlán','Bosques De Chapultepec (Polanco)','Independencia',2530,48148);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Riva Palacio','Altos Tepetlica','Cond 6',4795,69400);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Hueytlalpan','El Arbol','Platino',5724,90392);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Apatzingán','Doctores I','Plazuela 4 De La Plaza De La República',9473,23997);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Tumbalá','Compositores Mexicanos','B. De Argel',1792,36257);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Tetecala','Ajusco I','Ret. B. Italia',9754,82287);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Nogales','Ctm Vii Culhuacan (U Hab)','Cda. Lirio',7119,91227);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Camarón de Tejeda','Alamos I','Blanca Flor',2325,90693);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Yosoyúa','Colinas Del Bosque-Las Tortolas','Gratitud',9227,99628);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Sultepec','25 De julio','Plazuela 1 Plaza De Andalucia',2609,35032);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Atlequizayan','El Ruedo','Popocatépetl',1075,26948);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','Huamantla','Campestre Churubusco','Atlati',2016,81650);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','San Juan Evangelista','Barranca Seca','Cemelotl',6133,53157);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Taniche','Del Gas (Ampl)','Nicolás Bravo',2841,16649);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Mazatán','Acueducto De Guadalupe (Rdcial)','Adiós',4809,38835);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Lagunas','De Tarango (Rncda)','Valle De Las Animas',109,33943);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Yaxkukul','El Rosario A (U Hab)','De La Unión',6117,35784);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Distrito Federal','Gustavo A. Madero','Cosmopolita','Crisantemo',3787,48476);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Mezquital del Oro','El Rosario','Del Tesoro',1371,24508);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Ixhuacán de los Reyes','2 De octubre','Capulines',8925,42331);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Turicato','Coltongo','Pte. 25',9040,97910);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','San Lucas','Adolfo Lopez Mateos','Pte. 10',1149,49812);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Sebastián Ixcapa','Arboledas De Cuautepec (Ampl)','Cuauhtémoc Poniente',2415,81301);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Francisco Ixhuatán','Apatlaco','Valle De México',4537,91794);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Durango','Vicente Guerrero','El Eden','Gardenia',4220,81888);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','La Independencia','Corpus Curisty Ampl Xocomecatla','La Zandunga',1845,39208);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Guanajuato','26 De julio','Gral. E. Gutierrez',7554,94487);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Amixtlán','Centro Ii','Oriente 29',679,52155);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Juchique de Ferrer','Del Valle V','Castañeda',1288,62415);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Miguel de Allende','Acacias','Geografía',1789,17515);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Colima','Villa de Álvarez','El Yaqui','Lago Wetter',5018,34384);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Zacatlán','Acacias','Segunda Vicente Mendiola',4290,36945);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Homún','El Triangulo','Coral',1073,13334);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Nogales','Cuadrante De San Francisco','Cda. Lirio',3433,99691);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Antonio Tepetlapa','Axotla','Valle De Lierp',4235,72189);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','San José del Rincón','25 De julio','Plazuela 4 De Av. De Las 3 Culturas',1923,35105);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Santiago Tulantepec de Lugo Guerrero','Conjunto Habitacional Pedregal Del Lago','Manzanos',6796,69978);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Banderilla','Degollado Chico','Bugambilia',4720,21840);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Lerdo de Tejada','Conjunto Habitacional Pedregal Del Lago','Castillo De Chapultepec',9528,67718);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Yavesía','Belen De Las Flores','Gonzalo López',2189,59333);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Florencio Villarreal','Ctm Viii Culhuacan (U Hab)','Higinio Guerra',129,64533);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Alpoyeca','Benito Juarez','Hda. Del Peñón',8774,28885);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tula de Allende','Agricola Oriental Viii','Merida',6739,37367);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Coronango','Chalma De Guadalupe I','Oriente 47',104,84575);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','El Plateado de Joaquín Amaro','10 De abril','De Los Patos',9778,77887);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Ocozocoautla de Espinosa','2a Ampliacion Santiago Acahualtepec Ii','Águila Negra',5865,99549);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Teocaltiche','El Reloj','Ote. 8',7044,79545);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Axtla de Terrazas','Belisario Dominguez','Acamaya',8766,41971);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Las Rosas','Atlantida','Alicia Alvarez (Pueblo Viejo)',1358,79922);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Las Margaritas','24 De abril','Aculman',6069,73477);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Chilón','Aragon Inguaran','Las Costeñas',7349,16605);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Jalcomulco','Bejero','Carmen Carrion',2677,71542);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Dzilam de Bravo','Anzures','Constitución 6 De Enero',1553,57810);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tlaxcala','San Jerónimo Zacualpan','Corredor Santa Fe','Balsas',3017,98036);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Tamasopo','2 De octubre','V. Santa Elena V. Krakatoa',9942,21551);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Unión Hidalgo','Albert','Norte 15',5616,50642);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Dzidzantún','Castillo Grande (Ampl)','Constitución',3269,81852);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Asunción Nochixtlán','Agricola Oriental Iii','Sta. Rosa',65,81519);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Soledad Etla','Asturias (Ampl)','Nardos',1381,18234);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santo Domingo Tepuxtepec','Concordia Zaragoza (U Hab)','Mariano Matamoros',1541,48144);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Jocotipac','Cove','Cerrada 9',9798,24146);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Miguel Tecomatlán','Belisario Dominguez','Cerrada 10',8884,70323);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Igualapa','El Arbolillo 2 (U Hab)','Huixquilucan',3722,72202);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Apatzingán','El Bosque Seccion Torres','Plazuela 4 De La Plaza De La República',7121,93995);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Tekax','Caltongo (Barr)','De Corregidora',9847,29544);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María la Asunción','El Arenal','Ejjido De Xico',6264,43595);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa Catarina Mechoacán','Alianza Popular Revolucionaria Poniente (U Hab)','De Tizapa',3227,44749);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Montecristo de Guerrero','Del Bosque','B. De Libano',2355,41729);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','El Naranjo','El Rosal','Acentlapalito',9682,14271);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Chiautla','Cruz Del Farol','Plaza De Andalucia',643,66083);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','El Tule','Aguilera','Cordobanes',2422,27380);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tuxpan','Centro I','Pte. 26',8234,99069);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Huajolotitlán','Chichicaspatl','Juan Fernández Albarrán',6230,12215);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Zontecomatlán de López y Fuentes','Del Gas (Ampl)','Ciruelos (Italia)',7787,30208);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Soledad de Graciano Sánchez','Ecologica Novedades Impacto (U Hab)','V. San Martin (V. Jocotitlán)',1970,65232);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Sebastián Tecomaxtlahuaca','Ctm X Culhuacan (U Hab)','De Cuitláhuac',3769,23746);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Tultepec','Benito Juarez','Plazuela 3 De Av. De Las 3 Culturas',7759,57943);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Progreso de Obregón','Aaron Saenz','Manuel Bernal',62,48517);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Ocopetatillo','Ejercito De Oriente (U Hab) Ii','Ciprés',6062,40171);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Jiménez del Teul','Emiliano Zapata (Ampl)','Del Pocito',1698,68639);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Cuquío','Degollado','Netzahualcoyotl',4364,35647);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Quiegolani','Chinampac De Juarez Iii','Francisco J. Múgica',1470,89037);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Juan Lachao','Centro Viii','Villa Guerrero',4868,44278);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Ixcaquixtla','Belisario Dominguez','Portal Del Agua',2090,59935);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','San Lucas','Campestre Churubusco','Pte. 10',6066,83593);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','La Compañía','Degollado Chico','Tepepulco',1268,87037);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Acatlán de Pérez Figueroa','Canutillo Predio La Presa','Sta. María',4962,35444);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Tapilula','Del Valle Ii','B. Austria',3370,91268);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Quintana Roo','Tulum','Cazulco (Barr)','Tlaxcaltecas',3660,43805);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Degollado','Copilco El Alto','Nicolas Bravo',5252,48821);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Tlacoachistlahuaca','10 De abril','Iztapalapa',1328,82550);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Luis de la Paz','Emiliano Zapata (U Hab)','Guadalupe',3688,63146);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Otzoloapan','Anahuac Peralitos','Plazuela 1 De Av. Plaza De Aragón',8442,95142);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Andrés Huayápam','El Mirador - Santa Catarina','Valle Del Amazonas',8227,66348);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santo Domingo Tlatayápam','Azteca','Martínez Calderón',7333,32598);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Cristóbal Suchixtlahuaca','El Carmen','Valle Del Vistula',1699,65794);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Tlahuitoltepec','Del Valle Vi','General J. M. Santos',2804,44311);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Zaragoza','6 De junio','Acapulco',9700,15353);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santiago Zacatepec','Cuauhtemoc','Magnolia',9873,89687);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Esteban Atatlahuca','Arboledas','Valle Del Zambezi',8694,78908);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Temascalcingo','5to Tramo De 20 De Noviembre','Plazuela 24 De Av. Plaza De Aragón',9447,66332);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Agustín Tlacotepec','Alvaro Obregon','Valle De Iraguadi',2076,55934);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Vega de Alatorre','El Parque De Coyoacan (Fracc)','Cinta Larga',6067,41128);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Progreso de Obregón','Cocoyotes','Manuel Bernal',9225,16650);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Taxco de Alarcón','Ctm X Culhuacan (U Hab)','Isacar',6907,44058);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Tezontepec de Aldama','Chalma De Guadalupe I','Marieta',2459,77871);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Axtla de Terrazas','El Rosedal Ii','Acamaya',34,64215);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Molinos','Acueducto','Chiapas',2603,83686);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Yucatán','Tekit','Canutillo(Aguascalientes)','De Cotolin',1483,99194);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Hidalgo','Emiliano Zapata (U Hab)','Apatli',4773,37155);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','General Zaragoza','Barranca Seca','Sergio',6395,64213);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','San Felipe','Cuitláhuac 1 Y 2 (U Hab)','Gral Vicente Guerrero',5145,32511);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','La Huerta','Artes Graficas','Nte. 2',5984,70443);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Huamuxtitlán','Cocoyotes (Ampl)','Horacio Zuñiga',6137,66990);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Tlazazalca','Ejto Constitucionalista,Supermanzana Iii (U Hab)','Pte. 22',6041,14680);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Agustín Loxicha','Agricola Metropolitana','Valle De Huallaga',2363,19220);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Meoqui','Ejto Constitucionalista','Cond 20',2829,17096);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Veracruz','Ejercito De Oriente (U Hab) I','Cipatli',8680,80897);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Tepetzintla','Corpus Curisty Ampl Xocomecatla','Chabacano',95,67938);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Jilotzingo','Barros Sierra','Plazuela 10 De Av. De Las 3 Culturas',5913,82699);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chihuahua','Madera','Barranca Seca','Cond 16',890,36865);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Coatepec Harinas','Arboledas Del Sur','Pino',9098,48324);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','San Nicolás Buenos Aires','El Santuario (Ampl)','República De Uruguay',9785,25324);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('San Luis Potosí','Villa de Guadalupe','Emiliano Zapata (Ampl)','Abundio Gomez',6232,12754);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Isla','Campestre Potrero','Capiro',1410,29444);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Hualahuises','7 De julio','Siete Leguas',9977,15873);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Mapastepec','Campamento 2 De Octubre I','Acequia',9981,56706);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Trinidad García de la Cadena','Carmen Serdan','Del Oro',8513,31187);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Xayacatlán de Bravo','Art 4to Constitucional (U Hab)','Santo Tomás',5774,65638);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Jáltipan','Acueducto','Carmen Ocon Veloz',7493,20330);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Yahualica','El Arenal 4a Seccion','México Lindo',1526,36740);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Querétaro','Ezequiel Montes','Canal Once (U Hab)','Solidaridad (Tejones)',3965,23369);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Tuzamapan de Galeana','Agricola Oriental I','Santa Lucía',7491,47332);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Oriental','Cuauhtemoc','Privada 12',8904,70404);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Tetecala','Artes Graficas','Ret. B. Italia',125,61535);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Coscomatepec','El Molinito','Callejón Tres Estrellas',5540,95304);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Altamirano','Cuauhtemoc','Lago Zirahuen',667,22123);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tabasco','Tenosique','Diamante','Andador A Norte',7835,44716);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Ayapango','Del Valle Iii','Petroleos',7171,37900);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Perote','Cuautepec De Madero','Cda. Teotihuacan',1448,41049);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Nuevo Morelos','El Zacaton','Arenal',9719,91928);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','San Salvador','Chimalcoyoc','Manuel María Lares',4842,55525);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Tierra Blanca','Consejo Agrarista Mexicano Ii','Handel M. Gomez',8601,91553);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Tepalcingo','El Pocito','Ret. B. De Tanger',3450,50474);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','General Francisco R. Murguía','Cuitlahuac (U Hab)','De Los Olivos',332,84632);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sinaloa','Ahome','Canal Once (U Hab)','Acequia',9294,71258);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Marín','Emiliano Zapata (U Hab)','S. Juan',353,52363);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('México','Ocoyoacac','Copilco El Bajo','Plazuela 17 De Av. Plaza De Aragón',697,91105);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Sonora','Ures','Adolfo Ruiz Cortines I','Amalia Castillo',3918,52708);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Teuchitlán','El Zacaton','Otumba',6210,12685);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Tecalitlán','Copilco El Bajo','Ote. 40',6815,77786);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Nuevo León','Lampazos de Naranjo','Adolfo Ruiz Cortines I','Simeon',2354,31457);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Pedro Tidaá','Aguilera','Colima',4231,82279);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','San Lucas Camotlán','Chinampac De Juarez Ii','Adolfo López Mateos',9709,75143);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guanajuato','Guanajuato','Arboledas Politoco','Gral. E. Gutierrez',3615,71064);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Nicolás Ruíz','Copilco Universidad','Aeropuerto',9056,83209);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Nogales','El Toro','Cda. Lirio',5004,82540);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Tamaulipas','Nuevo Morelos','Del Valle I','Arenal',7547,22845);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Metapa','Campamento 2 De Octubre Ii','Administradores',1436,65552);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Las Vigas de Ramírez','Cola De Pato','Cda. Violeta',7558,15638);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','Santa María Yavesía','Country Club','Gonzalo López',1846,70235);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Churumuco','El Batan','Plazuela 6 De Av. San Marcos',1138,58127);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Briseñas','Cocoyotes','Plazuela 4 De Plaza Miravalle',8344,73434);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Amatlán de los Reyes','Asturias (Ampl)','Bosque De Los Pinos',7441,71123);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','Singuilucan','Centro Iv','Marcela Barreto',1895,90087);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Morelos','Cuautla','Del Carmen','R. B. Jordania',3921,28655);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Puebla','Juan C. Bonilla','Alpes (Ampl)','Primavera',9854,28231);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Zacatecas','Pinos','5to Tramo De 20 De Noviembre','De Rosas',9172,31068);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Guerrero','Atoyac de Álvarez','El Bosque Seccion Torres','Hda. De Solis',2573,44804);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Oaxaca','La Trinidad Vista Hermosa','Ave Real','Norte 14-A',4239,46633);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Michoacán de Ocampo','Maravatío','Del Valle Iii','Poniente 22',34,54822);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Veracruz de Ignacio de la Llave','Texcatepec','Arturo Gamiz','Chalco',3869,65336);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','El Arenal','Agricultura','Monte Alto',6715,74582);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Jalisco','Cañadas de Obregón','Ejidos De San Pedro Martir Ii (Sur)','P. De Cedro',8356,19942);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Chiapas','Copainalá','Batallon De San Patricio (U Hab)','La Malagueña',1384,30769);
INSERT INTO dirTrabajadorCompania(estado,municipio,colonia,calle,numero,cp) VALUES ('Hidalgo','La Misión','Del Valle Vii','L. Zum',3827,90259);
