INSERT INTO marca(modelo,marca) VALUES ('MR2','Hummer');
INSERT INTO marca(modelo,marca) VALUES ('MKX','GMC');
INSERT INTO marca(modelo,marca) VALUES ('7 Series','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Diamante','Ford');
INSERT INTO marca(modelo,marca) VALUES ('H3','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('IPL G','GMC');
INSERT INTO marca(modelo,marca) VALUES ('Optima','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('Tacoma','Hummer');
INSERT INTO marca(modelo,marca) VALUES ('Solstice','Ram');
INSERT INTO marca(modelo,marca) VALUES ('Firebird','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Celica','Infiniti');
INSERT INTO marca(modelo,marca) VALUES ('Escort','Plymouth');
INSERT INTO marca(modelo,marca) VALUES ('Charger','GMC');
INSERT INTO marca(modelo,marca) VALUES ('Grand Am','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('Wrangler','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('QX','GMC');
INSERT INTO marca(modelo,marca) VALUES ('i-350','Lamborghini');
INSERT INTO marca(modelo,marca) VALUES ('F350','Subaru');
INSERT INTO marca(modelo,marca) VALUES ('Villager','Porsche');
INSERT INTO marca(modelo,marca) VALUES ('Boxster','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Tacoma Xtra','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Armada','Lotus');
INSERT INTO marca(modelo,marca) VALUES ('Skyhawk','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Legacy','Jeep');
INSERT INTO marca(modelo,marca) VALUES ('Scoupe','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Defender 110','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('MKS','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('Five Hundred','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Esprit','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Diablo','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Maxima','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Tribute','Jaguar');
INSERT INTO marca(modelo,marca) VALUES ('Rondo','Porsche');
INSERT INTO marca(modelo,marca) VALUES ('2500','BMW');
INSERT INTO marca(modelo,marca) VALUES ('SVX','Chrysler');
INSERT INTO marca(modelo,marca) VALUES ('I','Buick');
INSERT INTO marca(modelo,marca) VALUES ('A6','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Ram Van 1500','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('Freestar','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('Daewoo Lacetti','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('Yukon','Alfa Romeo');
INSERT INTO marca(modelo,marca) VALUES ('F250','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Accord','Honda');
INSERT INTO marca(modelo,marca) VALUES ('240SX','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Samurai','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('RX-7','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('NSX','Buick');
INSERT INTO marca(modelo,marca) VALUES ('Trans Sport','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('626','Geo');
INSERT INTO marca(modelo,marca) VALUES ('MDX','Oldsmobile');
INSERT INTO marca(modelo,marca) VALUES ('Probe','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Altima','Jeep');
INSERT INTO marca(modelo,marca) VALUES ('200','Ferrari');
INSERT INTO marca(modelo,marca) VALUES ('Brougham','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Tempo','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('TT','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Protege','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('LS','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('Trooper','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('X6 M','Lexus');
INSERT INTO marca(modelo,marca) VALUES ('Santa Fe','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Montana','Maserati');
INSERT INTO marca(modelo,marca) VALUES ('Challenger','Lexus');
INSERT INTO marca(modelo,marca) VALUES ('Odyssey','Infiniti');
INSERT INTO marca(modelo,marca) VALUES ('S8','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('SLK-Class','BMW');
INSERT INTO marca(modelo,marca) VALUES ('H1','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('DBS','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Tahoe','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('Mazda3','Chrysler');
INSERT INTO marca(modelo,marca) VALUES ('Express 2500','Honda');
INSERT INTO marca(modelo,marca) VALUES ('Integra','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('9-3','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Swift','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Escape','BMW');
INSERT INTO marca(modelo,marca) VALUES ('Bonneville','Austin');
INSERT INTO marca(modelo,marca) VALUES ('Impreza WRX','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Catera','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('G-Series G20','Infiniti');
INSERT INTO marca(modelo,marca) VALUES ('Explorer','Buick');
INSERT INTO marca(modelo,marca) VALUES ('Sunfire','Lexus');
INSERT INTO marca(modelo,marca) VALUES ('XF','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Ram 3500 Club','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('GranTurismo','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('HHR','Porsche');
INSERT INTO marca(modelo,marca) VALUES ('Ion','Honda');
INSERT INTO marca(modelo,marca) VALUES ('Grand Caravan','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Arnage','Ford');
INSERT INTO marca(modelo,marca) VALUES ('C-Class','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('C70','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Aerostar','Honda');
INSERT INTO marca(modelo,marca) VALUES ('Sonoma Club Coupe','Porsche');
INSERT INTO marca(modelo,marca) VALUES ('Town Car','Land Rover');
INSERT INTO marca(modelo,marca) VALUES ('Mustang','BMW');
INSERT INTO marca(modelo,marca) VALUES ('M3','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('Allroad','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('2500 Club Coupe','GMC');
INSERT INTO marca(modelo,marca) VALUES ('Versa','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('1 Series','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Grand Prix','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Landaulet','Kia');
INSERT INTO marca(modelo,marca) VALUES ('Matrix','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Colorado','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('G','BMW');
INSERT INTO marca(modelo,marca) VALUES ('Freelander','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('F-Series','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('E150','Buick');
INSERT INTO marca(modelo,marca) VALUES ('Type 2','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('6000','Suzuki');
INSERT INTO marca(modelo,marca) VALUES ('Civic','Hyundai');
INSERT INTO marca(modelo,marca) VALUES ('Insight','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Ram 2500 Club','Land Rover');
INSERT INTO marca(modelo,marca) VALUES ('A4','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('LHS','Hyundai');
INSERT INTO marca(modelo,marca) VALUES ('Crown Victoria','Jeep');
INSERT INTO marca(modelo,marca) VALUES ('Skylark','Oldsmobile');
INSERT INTO marca(modelo,marca) VALUES ('GTO','Ford');
INSERT INTO marca(modelo,marca) VALUES ('CTS','Ford');
INSERT INTO marca(modelo,marca) VALUES ('RSX','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('280ZX','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('5000S','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('LR4','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Liberty','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('4Runner','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Malibu','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('Q','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Truck','Acura');
INSERT INTO marca(modelo,marca) VALUES ('Enclave','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Sonata','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Range Rover Sport','Honda');
INSERT INTO marca(modelo,marca) VALUES ('XL-7','Bentley');
INSERT INTO marca(modelo,marca) VALUES ('Prelude','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('Range Rover','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('929','Buick');
INSERT INTO marca(modelo,marca) VALUES ('Tredia','Lincoln');
INSERT INTO marca(modelo,marca) VALUES ('Rapide','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('Supra','Panoz');
INSERT INTO marca(modelo,marca) VALUES ('Cultus','Honda');
INSERT INTO marca(modelo,marca) VALUES ('Corvette','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('458 Italia','Maserati');
INSERT INTO marca(modelo,marca) VALUES ('Neon','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Contour','Hyundai');
INSERT INTO marca(modelo,marca) VALUES ('G-Series G10','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('E-Class','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('Park Avenue','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Discovery','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('Pilot','Buick');
INSERT INTO marca(modelo,marca) VALUES ('XC70','Ford');
INSERT INTO marca(modelo,marca) VALUES ('760','Acura');
INSERT INTO marca(modelo,marca) VALUES ('LX','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('530','Hyundai');
INSERT INTO marca(modelo,marca) VALUES ('Reno','Maserati');
INSERT INTO marca(modelo,marca) VALUES ('SL-Class','BMW');
INSERT INTO marca(modelo,marca) VALUES ('Leone','Porsche');
INSERT INTO marca(modelo,marca) VALUES ('Ram Van 2500','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Highlander','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Echo','Chrysler');
INSERT INTO marca(modelo,marca) VALUES ('M-Class','Kia');
INSERT INTO marca(modelo,marca) VALUES ('Aveo','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('100','Buick');
INSERT INTO marca(modelo,marca) VALUES ('57','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('Quest','Infiniti');
INSERT INTO marca(modelo,marca) VALUES ('RX Hybrid','Audi');
INSERT INTO marca(modelo,marca) VALUES ('Suburban 2500','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('LeMans','Austin');
INSERT INTO marca(modelo,marca) VALUES ('Passat','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Genesis','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('RVR','Acura');
INSERT INTO marca(modelo,marca) VALUES ('Land Cruiser','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Firebird Formula','GMC');
INSERT INTO marca(modelo,marca) VALUES ('Dakota','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('944','Saturn');
INSERT INTO marca(modelo,marca) VALUES ('Vision','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('Aerio','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Ram 1500 Club','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Suburban 1500','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Parisienne','Mitsubishi');
INSERT INTO marca(modelo,marca) VALUES ('Alcyone SVX','Jaguar');
INSERT INTO marca(modelo,marca) VALUES ('GTI','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Ram Van B250','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('Savana 1500','Oldsmobile');
INSERT INTO marca(modelo,marca) VALUES ('Bronco','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Avalanche 2500','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Avenger','Volkswagen');
INSERT INTO marca(modelo,marca) VALUES ('Karif','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Cobalt SS','Mazda');
INSERT INTO marca(modelo,marca) VALUES ('E-Series','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('Concorde','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('Sable','Honda');
INSERT INTO marca(modelo,marca) VALUES ('S70','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('GS','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Continental','Volvo');
INSERT INTO marca(modelo,marca) VALUES ('Caprice','Ford');
INSERT INTO marca(modelo,marca) VALUES ('B-Series Plus','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Sienna','Oldsmobile');
INSERT INTO marca(modelo,marca) VALUES ('Sierra 3500','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Corolla','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('MP4-12C','Acura');
INSERT INTO marca(modelo,marca) VALUES ('Rodeo','Nissan');
INSERT INTO marca(modelo,marca) VALUES ('S-Class','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('3 Series','Pontiac');
INSERT INTO marca(modelo,marca) VALUES ('Roadmaster','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Jimmy','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('8 Series','Lexus');
INSERT INTO marca(modelo,marca) VALUES ('Forester','Isuzu');
INSERT INTO marca(modelo,marca) VALUES ('Galant','Acura');
INSERT INTO marca(modelo,marca) VALUES ('Edge','Mercury');
INSERT INTO marca(modelo,marca) VALUES ('S2000','Ford');
INSERT INTO marca(modelo,marca) VALUES ('900','Oldsmobile');
INSERT INTO marca(modelo,marca) VALUES ('Seville','Cadillac');
INSERT INTO marca(modelo,marca) VALUES ('Xterra','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Riviera','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Ranger','Ford');
INSERT INTO marca(modelo,marca) VALUES ('Montana SV6','Acura');
INSERT INTO marca(modelo,marca) VALUES ('Corrado','Suzuki');
INSERT INTO marca(modelo,marca) VALUES ('4000CS Quattro','Chevrolet');
INSERT INTO marca(modelo,marca) VALUES ('Silverado 1500','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('Impreza','Dodge');
INSERT INTO marca(modelo,marca) VALUES ('Escalade ESV','Mercedes-Benz');
INSERT INTO marca(modelo,marca) VALUES ('riolet','Volvo');
INSERT INTO marca(modelo,marca) VALUES ('F150','Hummer');
INSERT INTO marca(modelo,marca) VALUES ('Durango','Toyota');
INSERT INTO marca(modelo,marca) VALUES ('Pacifica','Hyundai');
INSERT INTO marca(modelo,marca) VALUES ('740','Lexus');
INSERT INTO marca(modelo,marca) VALUES ('Golf','Volkswagen');
